package uml
public class Goods{
}
/*
@startuml
class Goods{
 - id : String
 - name: String
 - quantity: String
 - weight : String
 - write : String
 ----
 + Goods()
 + Goods(String,String,String)
 ----
 +  getId() : String
 +  setId(String)
 +  getName() : String
 +  setName(String)
 +  getQuantity() : String
 +  setQuantity(String)
 +  getWeight() : String
 +  setWeight(String)
 +  getWrite() : String
 +  setWrite(String)
}

@enduml
 */